### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by matiaswp** [JohannesLares/gymapp#1]
Moi!

Kävin kokeilemassa sovellustasi herokussa. Sovelluksen idea on mielestäni todella hyvä ja sellainen mitä itsekkin tulisi varmaan käytettyä. Sovelluksen rakenne on mielestäni selkeä ja helposti navigoitava. Suurimmat virheet, jotka joskus myös heittää internal server erroria, löytyivät sovelluksessa olevista html-formeista. Esimerkiksi;
+ Rekisteröityessä, jos jättää nimen tyhjäksi, niin sovellus heittää erroria.
+ Treenisuunnitelmaa luodessa, jos jättää joitain kohtia tyhjiksi, niin sovellus heittää erroria.
+ Jos rekisteröityessä laittaa nimeksi pelkkiä välilyöntejä, niin sillä on mahdollista tehdä käyttäjä.

Eli kannattaa käydä läpi kaikki formit ja estää tyhjät syötteet. Mielestäni kannattaa myös laittaa rekisteröitymissivulle käyttäjänimelle ja salasanalle ohjepituudet (esim. "Salasana 6-16 merkkiä"). Tämä parantaisi rekisteröityessä käyttökokemusta. 

Nämä kun saa korjattua, niin sovellus on mielestäni todella hyvässä mallissa :D

**Comment by JohannesLares** [comment]
Kiitos näistä, kävin nuo bulletit läpi ja korjasin. Myös hieman fronttivalidointia ja `minlength`-atribuuttia lisäilin inputteihin.
